name: Rubocop

on:
  pull_request:
    # If updating `paths` then update rubocop-none.yml to match
    paths:
      - 'config/rubocop/**/*.yml'
      - '.rubocop.yml'
      - '**.arb'
      - '**.rake'
      - '**.rb'
      - '*.gemspec'
      - 'gemfiles/**/Gemfile*'
      - 'Gemfile*'
      - 'Rakefile'

env:
  RUBY_VERSION: ${{ vars.REVIEWDOG_RUBOCOP_RUBY_VERSION || vars.REVIEWDOG_RUBY_VERSION || '3.2' }}

jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: ${{ vars.REVIEWDOG_RUBOCOP_BUNDLE_WITHOUT || 'default development test release docs' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: reviewdog/action-rubocop@v2
        with:
          fail_on_error: true
          filter_mode: nofilter # added (default), diff_context, file, nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_install: true
          use_bundler: true
